apiVersion: v1
kind: Service
metadata:
  name: svc-minimal-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  
  selector:
    app: minimal-api